Repository hmrc/tai, pull requests merged in 2018-08, with the labels that each got.

#26 ST-136: API Endpoints for tax code history and tax code change in year
  app/uk/gov/hmrc/tai/config/ApplicationConfig.scala
  app/uk/gov/hmrc/tai/connectors/ApplicationUrls.scala
  app/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnector.scala
  app/uk/gov/hmrc/tai/controllers/taxCodeChange/TaxCodeChangeController.scala
  app/uk/gov/hmrc/tai/metrics/Metrics.scala
  app/uk/gov/hmrc/tai/model/TaxCodeHistory.scala
  app/uk/gov/hmrc/tai/model/TaxCodeRecord.scala
  app/uk/gov/hmrc/tai/model/enums/APITypes.scala
  app/uk/gov/hmrc/tai/model/tai/TaxYear.scala
  app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala
  app/uk/gov/hmrc/tai/util/TaiConstants.scala
  conf/app.routes
  conf/application.conf
  project/MicroServiceBuild.scala
  test/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnectorSpec.scala
  test/uk/gov/hmrc/tai/controllers/taxCodeChange/TaxCodeChangeControllerSpec.scala
  test/uk/gov/hmrc/tai/model/TaxCodeHistorySpec.scala
  test/uk/gov/hmrc/tai/model/TaxCodeRecordSpec.scala
  test/uk/gov/hmrc/tai/service/TaxAccountServiceSpec.scala
  test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceImplSpec.scala
  test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceSpec.scala
  test/uk/gov/hmrc/tai/util/WireMockHelper.scala
Labels: Review Completed

#29 ST-136: Revert operatedTaxCode to boolean
  app/uk/gov/hmrc/tai/model/TaxCodeRecord.scala
  test/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnectorSpec.scala
  test/uk/gov/hmrc/tai/controllers/taxCodeChange/TaxCodeChangeControllerSpec.scala
  test/uk/gov/hmrc/tai/model/TaxCodeRecordSpec.scala
  test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceImplSpec.scala
  test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceSpec.scala
Labels: Review Completed

#36 ST-154: Updated hasTaxCodeChanged for Many to Many journey
  app/uk/gov/hmrc/tai/config/ApplicationConfig.scala
  app/uk/gov/hmrc/tai/connectors/ApplicationUrls.scala
  app/uk/gov/hmrc/tai/connectors/BbsiConnector.scala
  app/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnector.scala
  app/uk/gov/hmrc/tai/controllers/taxCodeChange/TaxCodeChangeController.scala
  app/uk/gov/hmrc/tai/model/TaxCodeHistory.scala
  app/uk/gov/hmrc/tai/model/TaxCodeRecord.scala
  app/uk/gov/hmrc/tai/model/api/TaxCodeChangeRecord.scala
  app/uk/gov/hmrc/tai/service/AutoUpdatePayService.scala
  app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala
  app/uk/gov/hmrc/tai/util/DateTimeHelper.scala
  app/uk/gov/hmrc/tai/util/TaiConstants.scala
  conf/app.routes
  conf/application.conf
  it/uk/gov/hmrc/tai/integration/cache/connectors/CacheConnectorItSpec.scala
  test/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnectorSpec.scala
  test/uk/gov/hmrc/tai/controllers/taxCodeChange/TaxCodeChangeControllerSpec.scala
  test/uk/gov/hmrc/tai/model/TaxCodeHistorySpec.scala
  test/uk/gov/hmrc/tai/model/TaxCodeRecordSpec.scala
  test/uk/gov/hmrc/tai/service/TaxAccountServiceSpec.scala
  test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceImplSpec.scala
  test/uk/gov/hmrc/tai/util/WireMockHelper.scala
Labels: Review Completed, Team 8

#37 ST-154: Update API documentation for tax code change.
  README.md
  docs/taxaccount/tax-code-change-exists.md
  docs/taxaccount/tax-code-change.md
Labels: Team 8
